(()=>{
'use strict';
const C=window.TTT_CONFIG||{};const BACK=(C.backendUrl||'').replace(/\/$/,'');
const $=s=>document.querySelector(s), app=$('#app');
const state={mode:null,board:Array(9).fill(''),turn:'X',over:false,win:[],room:null,ws:null,me:localStorage.getItem('ttt_user_id')||crypto.randomUUID(),name:localStorage.getItem('ttt_name')||'Player',scores:JSON.parse(localStorage.getItem('ttt_scores')||'{"X":0,"O":0,"D":0}'),chat:[]};
localStorage.setItem('ttt_user_id',state.me);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function save(){localStorage.setItem('ttt_scores',JSON.stringify(state.scores));localStorage.setItem('ttt_name',state.name)}
function page(){app.innerHTML=`<div class="shell"><header class="top"><div><div class="brand">Tic Tac <span>Toe</span></div><div class="sub">Online • Local • AI</div></div><div class="row"><button class="btn" id="nameBtn">👤 ${esc(state.name)}</button><button class="btn" id="backendBtn">⚙ Server</button></div></header><main class="wrap"><section id="home" class="screen active"><div class="card"><h1>Play Tic Tac Toe</h1><p>Rebuilt as a portable static frontend. No Replit-only files, paths or runtime are required.</p><div class="grid"><button class="btn primary" data-mode="local">👥 Local Multiplayer</button><button class="btn" data-mode="easy">🤖 AI — Easy</button><button class="btn" data-mode="hard">🧠 AI — Hard</button><button class="btn" id="onlineBtn">🌐 Online Multiplayer</button></div><div class="notice">Online mode uses the backend URL configured in <b>config.js</b>. Local and AI modes work entirely on GitHub Pages.</div></div><div class="grid" style="margin-top:16px"><div class="card"><h3>🏆 Your Stats</h3><p>Wins: <b id="sx">${state.scores.X}</b> • Losses: <b id="so">${state.scores.O}</b> • Draws: <b id="sd">${state.scores.D}</b></p></div><div class="card"><h3>🔗 Guest Mode</h3><p>No account or server required.</p><a class="btn" href="guest.html">Play as Guest</a></div></div></section><section id="game" class="screen"><div class="card"><div class="row"><button class="btn" id="back">← Home</button><strong id="gameTitle">Game</strong><span class="muted" id="gameRoom"></span></div><div class="status" id="status"></div><div class="board" id="board"></div><div class="score" id="score"></div><div class="row" style="justify-content:center"><button class="btn primary" id="restart">New Game</button><button class="btn" id="copyRoom" style="display:none">Copy Room Code</button></div></div></section><section id="online" class="screen"><div class="panel"><div class="card"><div class="row"><button class="btn" id="onlineBack">← Home</button><h2>🌐 Online Multiplayer</h2></div><div id="onlineNotice" class="notice"></div><div class="row"><button class="btn primary" id="createRoom">Create Room</button><input class="input" id="joinCode" maxlength="8" placeholder="Room code"><button class="btn" id="joinRoom">Join</button></div><div id="roomBox" class="hidden"><p>Room code</p><div class="room" id="roomCode"></div><div class="board" id="onlineBoard"></div><div class="status" id="onlineStatus"></div><div class="row"><button class="btn" id="onlineRestart">Restart</button><button class="btn" id="voice">🎤 Voice</button></div></div></div><div class="card"><h3>💬 Chat</h3><div class="chat" id="chat"></div><div class="row" style="margin-top:8px"><input class="input" id="chatInput" maxlength="200" placeholder="Message..."><button class="btn" id="sendChat">Send</button></div></div></div></section></main><footer class="footer">Made by Safaan • GitHub Pages ready</footer></div>`;bindHome();}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active')}
function bindHome(){document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>startGame(b.dataset.mode));$('#onlineBtn').onclick=()=>openOnline();$('#nameBtn').onclick=()=>setName();$('#backendBtn').onclick=()=>setBackend();}
function setName(){const n=prompt('Your display name:',state.name);if(n&&n.trim()){state.name=n.trim().slice(0,30);save();page()}}
function setBackend(){const u=prompt('Backend URL (example: https://your-service.onrender.com):',BACK);if(u!==null){localStorage.setItem('ttt_backend_url',u.trim().replace(/\/$/,''));location.reload()}}
function startGame(mode){state.mode=mode;state.board=Array(9).fill('');state.turn='X';state.over=false;state.win=[];show('game');$('#gameTitle').textContent=mode==='local'?'Local Multiplayer':mode==='easy'?'AI — Easy':'AI — Hard';$('#gameRoom').textContent='';$('#copyRoom').style.display='none';renderBoard();renderStatus()}
function renderBoard(){const b=$('#board');b.innerHTML='';state.board.forEach((v,i)=>{const c=document.createElement('button');c.className='cell '+(v?v.toLowerCase():'')+(state.win.includes(i)?' win':'');c.textContent=v;c.onclick=()=>move(i);b.appendChild(c)})}
function lines(){return[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]}
function result(board){for(const l of lines())if(board[l[0]]&&board[l[0]]===board[l[1]]&&board[l[1]]===board[l[2]])return{winner:board[l[0]],line:l};if(board.every(Boolean))return{winner:'D',line:[]};return null}
function move(i){if(state.over||state.board[i])return;if(state.mode==='easy'||state.mode==='hard')state.board[i]=state.turn;else state.board[i]=state.turn;finishOrContinue();if(!state.over&&(state.mode==='easy'||state.mode==='hard')&&state.turn==='O')setTimeout(aiMove,250)}
function finishOrContinue(){const r=result(state.board);if(r){state.over=true;state.win=r.line;if(r.winner==='D')state.scores.D++;else if(r.winner==='X')state.scores.X++;else state.scores.O++;save();renderBoard();renderStatus();return}state.turn=state.turn==='X'?'O':'X';renderBoard();renderStatus()}
function renderStatus(){const s=state.over?(result(state.board)?.winner==='D'?'Draw!':result(state.board)?.winner+' wins!'):state.turn+' to move';$('#status').textContent=s;$('#score').textContent=`X ${state.scores.X}  •  O ${state.scores.O}  •  Draws ${state.scores.D}`}
function aiMove(){if(state.over)return;let i;if(state.mode==='easy'){const a=state.board.map((v,n)=>v?null:n).filter(v=>v!==null);i=a[Math.floor(Math.random()*a.length)]}else i=best(state.board);if(i==null)return;state.board[i]='O';finishOrContinue()}
function best(b){let bestScore=-Infinity,move=null;for(let i=0;i<9;i++)if(!b[i]){b[i]='O';const s=minimax(b,false);b[i]='';if(s>bestScore){bestScore=s;move=i}}return move}
function minimax(b,max){const r=result(b);if(r)return r.winner==='O'?10:r.winner==='X'?-10:0;let best=max?-Infinity:Infinity;for(let i=0;i<9;i++)if(!b[i]){b[i]=max?'O':'X';const s=minimax(b,!max);b[i]='';best=max?Math.max(best,s):Math.min(best,s)}return best+(max?0:0)}
async function api(path,opt={}){if(!BACK)throw Error('Backend is not configured');const r=await fetch(BACK+path,{...opt,headers:{'Content-Type':'application/json',...(opt.headers||{})}});if(!r.ok)throw Error(await r.text()||r.statusText);return r.json()}
function openOnline(){show('online');$('#onlineNotice').innerHTML=BACK?`Connected target: <b>${esc(BACK)}</b>`:'Online backend is not configured. Use ⚙ Server above after deploying server.py.';$('#roomBox').classList.add('hidden');connectWs()}
function wsUrl(){if(!BACK)return '';const u=new URL(BACK);u.protocol=u.protocol==='https:'?'wss:':'ws:';u.pathname='/api/ws';u.searchParams.set('userId',state.me);return u.toString()}
function connectWs(){if(!BACK)return;if(state.ws&&state.ws.readyState<2)return;try{state.ws=new WebSocket(wsUrl());state.ws.onopen=()=>$('#onlineNotice').innerHTML=`<span class="ok">● Connected</span> to ${esc(BACK)}`;state.ws.onclose=()=>$('#onlineNotice').innerHTML='<span class="warn">● Disconnected</span> — check the backend service';state.ws.onerror=()=>{};state.ws.onmessage=e=>onWs(JSON.parse(e.data))}catch(e){$('#onlineNotice').textContent=e.message}}
function send(o){if(state.ws&&state.ws.readyState===1)state.ws.send(JSON.stringify(o));else alert('Online server is not connected.')}
function createRoom(){connectWs();setTimeout(()=>send({type:'create',userId:state.me,name:state.name}),200)}
function joinRoom(){const code=$('#joinCode').value.trim().toUpperCase();if(code)send({type:'join',code,userId:state.me,name:state.name})}
function onWs(d){if(d.type==='created'){state.room=d.code;showRoom(d);send({type:'profile',name:state.name})}else if(d.type==='start'||d.type==='update'){showRoom(d);state.board=d.board||Array(9).fill('');state.turn=d.turn||'X';renderOnline()}else if(d.type==='gameover'){state.board=d.board||state.board;renderOnline();$('#onlineStatus').textContent=d.winner==='D'?'Draw!':d.winner+' wins!'}else if(d.type==='chat'){state.chat.push(d);renderChat()}else if(d.type==='error')$('#onlineNotice').innerHTML='<span class="err">'+esc(d.message||'Server error')+'</span>';else if(d.type==='opponent_left')$('#onlineStatus').textContent='Opponent left the room.'}
function showRoom(d){$('#roomBox').classList.remove('hidden');$('#roomCode').textContent=d.code||state.room;$('#gameRoom').textContent=d.code?'Room '+d.code:'';renderOnline()}
function renderOnline(){const b=$('#onlineBoard');if(!b)return;b.innerHTML='';state.board.forEach((v,i)=>{const c=document.createElement('button');c.className='cell '+(v?v.toLowerCase():'');c.textContent=v;c.onclick=()=>send({type:'move',index:i});b.appendChild(c)});$('#onlineStatus').textContent=state.turn?state.turn+' to move':''}
function renderChat(){const c=$('#chat');c.innerHTML=state.chat.map(m=>`<div class="msg"><b>${esc(m.name||'Player')}</b> ${esc(m.text||'')}</div>`).join('');c.scrollTop=c.scrollHeight}
function sendChat(){const i=$('#chatInput'),t=i.value.trim();if(t){send({type:'chat',text:t,name:state.name});i.value=''}}
function wire(){document.addEventListener('click',e=>{if(e.target.id==='back'){page()}if(e.target.id==='restart')startGame(state.mode);if(e.target.id==='onlineBack'){if(state.ws)state.ws.close();page()}if(e.target.id==='createRoom')createRoom();if(e.target.id==='joinRoom')joinRoom();if(e.target.id==='onlineRestart')send({type:'restart'});if(e.target.id==='sendChat')sendChat();if(e.target.id==='copyRoom'&&state.room)navigator.clipboard?.writeText(state.room)});document.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.id==='chatInput')sendChat()})}
page();wire();
})();
